{{- if and .Values.networkPolicies.enabled .Values.admin.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "matrix.fullname" . }}-admin
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.admin.labels" . | indent 4}}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matrix.fullname" . }}-admin
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
{{- end }}
