{{- if .Values.dimension.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-dimension
  labels:
{{ include "matrix.labels" . | indent 4 }}
{{ include "matrix.dimension.labels" . | indent 4 }}
spec:
  type: {{ .Values.dimension.service.type }}
  ports:
    - port: {{ .Values.dimension.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-dimension
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
